title: Mlnck
author:
  name: Jack Melnick
  email: 'jack@mlnck.me'
metadata:
    description: 'Online Personal Brand of Jack Melnick'
taxonomies: [category,tags,author]

redirects:
#  '/redirect-test': '/'                         # Redirect test goes to home page
#  '/old/(.*)': '/new/$1'                        # Would redirect /old/my-page to /new/my-page

routes:
#  '/something/else': '/blog/sample-3'         # Alias for /blog/sample-3
#  '/new/(.*)': '/blog/$1'                     # Regex any /new/my-page URL to /blog/my-page Route

blog:
  route: '/blog'                            # Custom value added (accessible via system.blog.route)
