title: Mlnck
default_lang: en
author:
  name: 'Jack Melnick'
  email: jack@mlnck.me
taxonomies:
  - category
  - tags
  - author
metadata:
  description: 'Online Personal Brand of Jack Melnick'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
categoryfilters:
  Blog: '#FF00FF'
  Kickoff: '#782DFF'
  Progress: '#00FFE4'
  Completion: '#00FF4B'
  Playground: '#F9A64C'
  Writing: '#FF665C'
  Stream: '#FFE500'
  Tags: '#A4A4A7'
